/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://gkfqz3zx5nc6dms3linasen24e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hh54kfhomjbcrcvhyxjohaxomm",
    "aws_cognito_identity_pool_id": "us-east-1:4fe893f5-db7a-4f3c-982a-7a11278b9fc1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ucam5wLOK",
    "aws_user_pools_web_client_id": "lvsotoltf7h77u9d4vgic5sf",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "paywind-storage-7bcf0a33202343-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
