/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://zpkxtu5gh5ho5csyrv6crp36eq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rkdzy6hrsbhspec6lfabpfxhpu",
    "aws_cognito_identity_pool_id": "us-east-1:445235c4-7176-498c-a66b-d84d56d2a1d2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mupKiBAbk",
    "aws_user_pools_web_client_id": "6lcn1tnflfqttum3nlukgtbu1j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "paywind-storage-bc1fc3f7210629-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
